# Setup
title:               meleu
tagline:             'Today I Learned'
description:         'A microblog to dump small things I've been learning'
url:                 http://meleu.github.io/lanyon
baseurl:             '/lanyon/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              meleu
  url:               https://twitter.com/meleuzord
  email:             meleu.dev (at) gmail dot com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
